title: Xterm.js
email: paris@sourcelair.com
description: Terminal front-end component written in JavaScript that works in the browser.
baseurl: ''
url: 'http://xtermjs.org'

version: '5.5'

markdown: kramdown

defaults:
  - {scope: {type: docs}, values: {layout: docs}}

include:
  - _pages

exclude:
  - gulpfile.js
  - package.json
  - node_modules/
  - bin/
  - vendor/

collections:
  docs:
    output: true
    permalink: '/docs/:path/'

relative_links:
  collections: true
